checkExisting = True
isInteractive = True
checkforDoi = True
checkForArxiv = True
saveAfterElements = 100
fileLiteraturBib = "../data/literature.bib"
folderPDFPrefix = "../data/"
folderTEIPrefix = "../teibib/"
fileGraphModel = "../data/graph-model.json"
bibKeyPrefix = "reviz_key"
bibRefPrefix = "reviz_ref"
bibKeyID = "ID"  # "bibtex_key"
bibKeyType = "ENTRYTYPE"  # "document_type"
bibKeyFile = "file"  # "note"
bibKeyTitle = "title"
bibKeyAuthor = "author"
bibKeyDoi = "doi"
bibKeyUrl = "url"
bibKeyYear = "year"
bibKeyEprint = "eprint"
bibKeyCheckedDoi = "reviz_doi"
bibKeyCheckedTei = "reviz_tei"
bibKeyCheckedEprint = "reviz_eprint"
maxManualQueueLen = 100
